batch_size: 64
lr: 0.01
epochs: 10
momentum: 0.9
weight_decay: 0.0005
scheduler: "cosine"
checkpoint_drive_path: "/content/drive/MyDrive/mldl_checkpoints/centralized_cosine.pth"
checkpoint_path: "./checkpoints/centralized_cosine.pth"
log_path: "./logs/centralized_cosine.json"
log_drive_path: "/content/drive/MyDrive/mldl_checkpoints/centralized_cosine.json"
