batch_size: 64
lr: 0.005
epochs: 20
momentum: 0.9
weight_decay: 0.001
scheduler: "step"
step_size: 3
gamma: 0.1
checkpoint_path: "./checkpoints/centralized_step_2.pth"
log_path: "./logs/centralized_step_2.json"
checkpoint_drive_path: "/content/drive/MyDrive/mldl_checkpoints/centralized_step_2.pth"
log_drive_path: "/content/drive/MyDrive/mldl_checkpoints/centralized_step_2.json"
early_stopping_patience: 3
best_model_path: "./checkpoints/best_model_centralized_step_2.pth"
best_model_drive_path: "/content/drive/MyDrive/mldl_checkpoints/best_model_centralized_step_2.pth"
