batch_size: 64
fisher_batch_size: 1  
epochs: 20
lr: 0.01
weight_decay: 0.0005
early_stopping_patience: 3
sparsity_ratio: 0.3  
calibration_rounds: 5
mask_calibration_rule: sensitivity_least   #or sensitivity_least, magnitude_highest, magnitude_lowest, random
checkpoint_path: ./checkpoints/centralized_sparse_6.pth
checkpoint_drive_path: /content/drive/MyDrive/mldl_checkpoints/centralized_sparse_6.pth
log_path: ./logs/centralized_sparse_6.json
log_drive_path: /content/drive/MyDrive/mldl_checkpoints/centralized_sparse_6.json
