batch_size: 64
lr: 0.03
epochs: 10
momentum: 0.9
weight_decay: 0.0005
scheduler: "step"
step_size: 60
gamma: 0.1
checkpoint_path: "./checkpoints/centralized_step.pth"
log_path: "./logs/centralized_step.json"
