batch_size: 64
lr: 0.005
epochs: 20
momentum: 0.9
weight_decay: 0.0005
scheduler: "cosine"
checkpoint_path: "./checkpoints/centralized_cosine_4.pth"
checkpoint_drive_path: "/content/drive/MyDrive/mldl_checkpoints/centralized_cosine_4.pth"
log_path: "./logs/centralized_cosine_4.json"
log_drive_path: "/content/drive/MyDrive/mldl_checkpoints/centralized_cosine_4.json"
early_stopping_patience: 3
