batch_size: 64
lr: 0.001
epochs: 20
momentum: 0.9
weight_decay: 0.0005
scheduler: "step"
step_size: 3
gamma: 0.1
checkpoint_path: "./checkpoints/centralized_step_3.pth"
log_path: "./logs/centralized_step_3.json"
checkpoint_drive_path: "/content/drive/MyDrive/mldl_checkpoints/centralized_step_3.pth"
log_drive_path: "/content/drive/MyDrive/mldl_checkpoints/centralized_step_3.json"
early_stopping_patience: 3
