batch_size: 64
fisher_batch_size: 1  
epochs: 15
lr: 0.01
weight_decay: 0.0005
early_stopping_patience: 3
calibration_rounds: 5
sparsity_ratio: 0.8 
mask_calibration_rule: sensitivity_most   #or sensitivity_least, magnitude_highest, magnitude_lowest, random
checkpoint_path: ./checkpoints/centralized_sparse_most.pth
checkpoint_drive_path: /content/drive/MyDrive/mldl_checkpoints/centralized_sparse_most.pth
log_path: ./logs/centralized_sparse_most.json
log_drive_path: /content/drive/MyDrive/mldl_checkpoints/centralized_sparse_most.json
