batch_size: 64
lr: 0.01
epochs: 20
momentum: 0.9
weight_decay: 0.0005
scheduler: "cosine"
checkpoint_drive_path: "/content/drive/MyDrive/mldl_checkpoints/centralized_cosine_1.pth"
checkpoint_path: "./checkpoints/centralized_cosine_1.pth"
log_path: "./logs/centralized_cosine_1.json"
log_drive_path: "/content/drive/MyDrive/mldl_checkpoints/centralized_cosine_1.json"
early_stopping_patience: 3
best_model_path: "./checkpoints/best_model_centralized_cosine_1.pth"
best_model_drive_path: "/content/drive/MyDrive/mldl_checkpoints/best_model_centralized_cosine_1.pth"
