K: 100          
C: 0.1        
J: 4            
rounds: 100     
sharding: "iid"
lr: 0.01                
batch_size: 32          
calibration_interval: 10
mask_calibration_rule: "sensitivity_most" #options: "sensitivity_least", "magnitude_highest", "magnitude_lowest", "random"
sparsity_ratio: 0.5
save_every: 10  
checkpoint_path: "./checkpoints/federated_sparse_idd_2.pth"
log_path: "./logs/federated_sparse_idd_2.json"
checkpoint_drive_path: "content/drive/MyDrive/mldl_checkpoints/federated_sparse_idd_2.pth"
log_drive_path: "content/drive/MyDrive/mldl_checkpoints/federated_sparse_idd_2.json"
