K: 100          
C: 0.1        
J: 4           
Nc: 50
rounds: 30    
sharding: "noniid"
lr: 0.01                
batch_size: 32          
calibration_rounds: 5
mask_calibration_rule: "magnitude_lowest" #sensitivity_least,sensitivity_most, magnitude_highest, random
sparsity_ratio: 0.8
save_every: 1
checkpoint_path: "./checkpoints/federated_sparse_nonidd_magnitude_lowest.pth"
log_path: "./logs/federated_sparse_nonidd_magnitude_lowest.json"
checkpoint_drive_path: "content/drive/MyDrive/mldl_checkpoints/federated_sparse_nonidd_magnitude_lowest.pth"
log_drive_path: "content/drive/MyDrive/mldl_checkpoints/federated_sparse_nonidd_magnitude_lowest.json"
