K: 100          
C: 0.1        
J: 4            
rounds: 30
sharding: "iid"
lr: 0.01                
batch_size: 32          
calibration_rounds: 5
mask_calibration_rule: "random" #sensitivity_least, magnitude_highest, magnitude_lowest, sensitivity_most
sparsity_ratio: 0.8
save_every: 1
checkpoint_path: "./checkpoints/federated_sparse_idd_random.pth"
log_path: "./logs/federated_sparse_idd_random.json"
checkpoint_drive_path: "content/drive/MyDrive/mldl_checkpoints/federated_sparse_idd_random.pth"
log_drive_path: "content/drive/MyDrive/mldl_checkpoints/federated_sparse_idd_random.json"
