K: 100          
C: 0.1        
J: 4            
rounds: 30 
sharding: "iid"
lr: 0.01                
batch_size: 32          
calibration_rounds: 8
mask_calibration_rule: "sensitivity_least" #options: "sensitivity_most", "magnitude_highest", "magnitude_lowest", "random"
sparsity_ratio: 0.5
save_every: 1
checkpoint_path: "./checkpoints/federated_sparse_idd_3.pth"
log_path: "./logs/federated_sparse_idd_3.json"
checkpoint_drive_path: "/content/drive/MyDrive/mldl_checkpoints/federated_sparse_idd_3.pth"
log_drive_path: "/content/drive/MyDrive/mldl_checkpoints/federated_sparse_idd_3.json"
