K: 100          
C: 0.1        
J: 4            
rounds: 100     
sharding: "iid"
lr: 0.01                
batch_size: 32          
calibration_rounds: 10
mask_calibration_rule: "sensitivity_least" #options: "sensitivity_most", "magnitude_highest", "magnitude_lowest", "random"
sparsity_ratio: 0.8
save_every: 10  
checkpoint_path: "./checkpoints/federated_sparse_idd_2.pth"
log_path: "./logs/federated_sparse_idd_2.json"
checkpoint_drive_path: "content/drive/MyDrive/mldl_checkpoints/federated_sparse_idd_2.pth"
log_drive_path: "content/drive/MyDrive/mldl_checkpoints/federated_sparse_idd_2.json"
