K: 100
C: 0.1
J: 4
Nc: 1
rounds: 15
batch_size: 32
lr: 0.03
weight_decay: 0.0005
checkpoint_path: ./checkpoints/fedavg_model.pth
log_path: ./logs/federated_log.json
save_every: 1
sharding: "iid"  # or "noniid"
